-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.11.0.396.4
-- Module  Version: 5.7
-- Mon Jul 18 13:10:35 2022

-- parameterized module component declaration
component pll25m
    port (CLKI: in  std_logic; CLKOP: out  std_logic; 
        CLKOS: out  std_logic; CLKOS2: out  std_logic; 
        CLKOS3: out  std_logic; LOCK: out  std_logic);
end component;

-- parameterized module component instance
__ : pll25m
    port map (CLKI=>__, CLKOP=>__, CLKOS=>__, CLKOS2=>__, CLKOS3=>__, 
        LOCK=>__);
